#! /usr/bin/env bash

csc=$(which csc)

fsType="ext4"
pool="B"

function setup {
	cd $(dirname $0)
	export CSI_ENDPOINT="tcp://localhost:10000"
	export X_CSI_SECRETS="apiAddress=${STORAGE_API_ADDR}, username=${STORAGE_USERNAME}, password=${STORAGE_PASSWORD}"
}

setup
${csc} --params "fsType=${fsType},pool=${pool}" $@
