#! /usr/bin/env bash

#
# Usage: sanity-cli [all]
#
# Running ./sanity-cli
#     Will fail fast (-ginkgo.failFast) and use -ginkgo.focus based on TEST_FOCUS
#     Use `export TEST_FOCUS=<item>`, such as <item> = CreateVolume to limit test cases
#
# Running ./sanity-cli all
#     Will run all test cases and continue past failures
#

if [ -z ${1+x} ]; then
    opt=
else
    opt=$1
fi

echo ""
echo "[] sanity-cli $opt"


secretsTemplate="secrets.template.yml"
secrets="secrets.yml"
volumeTemplate="volume.template.yml"
volume="volume.yml"

set -e

function pause()
{
    echo ""
    read -s -n 1 -p "===== Press any key to contine ====="
    echo ""
}

function setup {
	cd $(dirname $0)
	set -a; . .env; set +a

    echo ""

	envsubst < ${secretsTemplate} > ${secrets}
    echo "===== ${secrets} ====="
    cat ${secrets}
    echo "===== END ====="

    echo ""

	envsubst < ${volumeTemplate} > ${volume}
    echo "===== ${volume} ====="
    cat ${volume}
    echo "===== END ====="
    pause
}

function setVariables()
{
    echo ""
    echo "env variables:"

    # export TEST_FOCUS=DeleteVolume
    # export TEST_FOCUS=CreateVolume

    test_focus=$TEST_FOCUS
    if [ -z "$test_focus" ]
    then
        test_focus=
    fi
    echo "-- TEST_FOCUS = $test_focus"
    pause
}

setVariables
setup

controller=unix:///var/run/csi-exos-x.seagate.com/csi-controller.sock
node=unix:///var/run/csi-exos-x.seagate.com/csi-node.sock
sanity=/home/seagate/github.com/kubernetes-csi/csi-test/cmd/csi-sanity/csi-sanity
# sanity=/home/seagate/github.com/jskazinski/csi-test/cmd/csi-sanity/csi-sanity
focus=${test_focus}

echo ""
echo "[] csi-sanity"

if [ "$opt" == "all" ]; then
    echo "sudo ${sanity} -csi.controllerendpoint ${controller} -csi.endpoint ${node} -csi.secrets ${secrets} -csi.testvolumeparameters ${volume} > sanity.log"
    sudo ${sanity} -csi.controllerendpoint ${controller} -csi.endpoint ${node} -csi.secrets ${secrets} -csi.testvolumeparameters ${volume} > sanity.log 
else
    echo "sudo ${sanity} -csi.controllerendpoint ${controller} -csi.endpoint ${node} -csi.secrets ${secrets} -ginkgo.focus \"${focus}\" -csi.testvolumeparameters ${volume} -ginkgo.failFast > sanity.log"
    sudo ${sanity} -csi.controllerendpoint ${controller} -csi.endpoint ${node} -csi.secrets ${secrets} -ginkgo.focus "${focus}" -csi.testvolumeparameters ${volume} -ginkgo.failFast > sanity.log 
fi

out=$?

exit ${out}
