apiVersion: storage.k8s.io/v1
kind: StorageClass
provisioner: csi-exos-x.seagate.com # Check pkg/driver.go, Required for the plugin to recognize this storage class as handled by itself.
volumeBindingMode: WaitForFirstConsumer # Prefer this value to avoid unschedulable pods (https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode)
allowVolumeExpansion: true
metadata:
  name: systems-storageclass # Choose the name that fits the best with your StorageClass.
parameters:
  # Secrets name and namespace, they can be the same for provisioner, controller-publish and controller-expand sections. node-publish secrets are for CHAP authentication
  csi.storage.k8s.io/provisioner-secret-name: seagate-exos-x-csi-secrets
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/controller-publish-secret-name: seagate-exos-x-csi-secrets
  csi.storage.k8s.io/controller-publish-secret-namespace: default
  csi.storage.k8s.io/controller-expand-secret-name: seagate-exos-x-csi-secrets
  csi.storage.k8s.io/controller-expand-secret-namespace: default
  csi.storage.k8s.io/node-publish-secret-name:  seagate-exos-x-csi-secrets  # Secrets for CHAP authentication
  csi.storage.k8s.io/node-publish-secret-namespace: default   # If you are not using CHAP authentication, these lines may be omitted. 
  csi.storage.k8s.io/fstype: ext4 # Desired filesystem
  pool: A # Pool to use on the IQN to provision volumes
  volPrefix: csi # Desired prefix for volume naming. 3 chars max; an underscore will be appended.
  storageProtocol: iscsi # The storage interface (iscsi, fc, sas) being used for storage i/o
