// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.2
// source: pkg/node_service/node_servicepb/node_rpc.proto

package node_servicepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	GetInitiators(ctx context.Context, in *InitiatorRequest, opts ...grpc.CallOption) (*Initiators, error)
	NotifyUnmap(ctx context.Context, in *UnmappedVolume, opts ...grpc.CallOption) (*Ack, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) GetInitiators(ctx context.Context, in *InitiatorRequest, opts ...grpc.CallOption) (*Initiators, error) {
	out := new(Initiators)
	err := c.cc.Invoke(ctx, "/node_service.NodeService/GetInitiators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) NotifyUnmap(ctx context.Context, in *UnmappedVolume, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/node_service.NodeService/NotifyUnmap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility
type NodeServiceServer interface {
	GetInitiators(context.Context, *InitiatorRequest) (*Initiators, error)
	NotifyUnmap(context.Context, *UnmappedVolume) (*Ack, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNodeServiceServer struct {
}

func (UnimplementedNodeServiceServer) GetInitiators(context.Context, *InitiatorRequest) (*Initiators, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInitiators not implemented")
}
func (UnimplementedNodeServiceServer) NotifyUnmap(context.Context, *UnmappedVolume) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyUnmap not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_GetInitiators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetInitiators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node_service.NodeService/GetInitiators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetInitiators(ctx, req.(*InitiatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_NotifyUnmap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmappedVolume)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).NotifyUnmap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node_service.NodeService/NotifyUnmap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).NotifyUnmap(ctx, req.(*UnmappedVolume))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "node_service.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInitiators",
			Handler:    _NodeService_GetInitiators_Handler,
		},
		{
			MethodName: "NotifyUnmap",
			Handler:    _NodeService_NotifyUnmap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/node_service/node_servicepb/node_rpc.proto",
}
