// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.2
// source: pkg/node_service/node_servicepb/node_rpc.proto

package node_servicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitiatorType int32

const (
	InitiatorType_UNSPECIFIED InitiatorType = 0
	InitiatorType_FC          InitiatorType = 1
	InitiatorType_SAS         InitiatorType = 2
	InitiatorType_ISCSI       InitiatorType = 3
)

// Enum value maps for InitiatorType.
var (
	InitiatorType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "FC",
		2: "SAS",
		3: "ISCSI",
	}
	InitiatorType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"FC":          1,
		"SAS":         2,
		"ISCSI":       3,
	}
)

func (x InitiatorType) Enum() *InitiatorType {
	p := new(InitiatorType)
	*p = x
	return p
}

func (x InitiatorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InitiatorType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_node_service_node_servicepb_node_rpc_proto_enumTypes[0].Descriptor()
}

func (InitiatorType) Type() protoreflect.EnumType {
	return &file_pkg_node_service_node_servicepb_node_rpc_proto_enumTypes[0]
}

func (x InitiatorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InitiatorType.Descriptor instead.
func (InitiatorType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_node_service_node_servicepb_node_rpc_proto_rawDescGZIP(), []int{0}
}

type InitiatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type InitiatorType `protobuf:"varint,1,opt,name=type,proto3,enum=node_service.InitiatorType" json:"type,omitempty"`
}

func (x *InitiatorRequest) Reset() {
	*x = InitiatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_node_service_node_servicepb_node_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitiatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatorRequest) ProtoMessage() {}

func (x *InitiatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_node_service_node_servicepb_node_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatorRequest.ProtoReflect.Descriptor instead.
func (*InitiatorRequest) Descriptor() ([]byte, []int) {
	return file_pkg_node_service_node_servicepb_node_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *InitiatorRequest) GetType() InitiatorType {
	if x != nil {
		return x.Type
	}
	return InitiatorType_UNSPECIFIED
}

type Initiators struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Initiators []string `protobuf:"bytes,1,rep,name=initiators,proto3" json:"initiators,omitempty"`
}

func (x *Initiators) Reset() {
	*x = Initiators{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_node_service_node_servicepb_node_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Initiators) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Initiators) ProtoMessage() {}

func (x *Initiators) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_node_service_node_servicepb_node_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Initiators.ProtoReflect.Descriptor instead.
func (*Initiators) Descriptor() ([]byte, []int) {
	return file_pkg_node_service_node_servicepb_node_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *Initiators) GetInitiators() []string {
	if x != nil {
		return x.Initiators
	}
	return nil
}

type UnmappedVolume struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumeName string `protobuf:"bytes,1,opt,name=volumeName,proto3" json:"volumeName,omitempty"`
}

func (x *UnmappedVolume) Reset() {
	*x = UnmappedVolume{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_node_service_node_servicepb_node_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnmappedVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmappedVolume) ProtoMessage() {}

func (x *UnmappedVolume) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_node_service_node_servicepb_node_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmappedVolume.ProtoReflect.Descriptor instead.
func (*UnmappedVolume) Descriptor() ([]byte, []int) {
	return file_pkg_node_service_node_servicepb_node_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *UnmappedVolume) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack int32 `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_node_service_node_servicepb_node_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_node_service_node_servicepb_node_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_pkg_node_service_node_servicepb_node_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetAck() int32 {
	if x != nil {
		return x.Ack
	}
	return 0
}

var File_pkg_node_service_node_servicepb_node_rpc_proto protoreflect.FileDescriptor

var file_pkg_node_service_node_servicepb_node_rpc_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x70, 0x6b, 0x67, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x70,
	0x62, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x43,
	0x0a, 0x10, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1b, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x2c, 0x0a, 0x0a, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72,
	0x73, 0x22, 0x30, 0x0a, 0x0e, 0x55, 0x6e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x56, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x17, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x2a, 0x3c, 0x0a, 0x0d,
	0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a,
	0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x06,
	0x0a, 0x02, 0x46, 0x43, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x41, 0x53, 0x10, 0x02, 0x12,
	0x09, 0x0a, 0x05, 0x49, 0x53, 0x43, 0x53, 0x49, 0x10, 0x03, 0x32, 0x9c, 0x01, 0x0a, 0x0b, 0x4e,
	0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x1e, 0x2e, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0b, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x55, 0x6e, 0x6d, 0x61, 0x70, 0x12, 0x1c, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x6e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x56, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x1a, 0x11, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x41, 0x63, 0x6b, 0x22, 0x00, 0x42, 0x57, 0x5a, 0x55, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x65, 0x61, 0x67, 0x61, 0x74, 0x65, 0x2f,
	0x73, 0x65, 0x61, 0x67, 0x61, 0x74, 0x65, 0x2d, 0x65, 0x78, 0x6f, 0x73, 0x2d, 0x78, 0x2d, 0x63,
	0x73, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x75, 0x66, 0x66,
	0x65, 0x72, 0x73, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_node_service_node_servicepb_node_rpc_proto_rawDescOnce sync.Once
	file_pkg_node_service_node_servicepb_node_rpc_proto_rawDescData = file_pkg_node_service_node_servicepb_node_rpc_proto_rawDesc
)

func file_pkg_node_service_node_servicepb_node_rpc_proto_rawDescGZIP() []byte {
	file_pkg_node_service_node_servicepb_node_rpc_proto_rawDescOnce.Do(func() {
		file_pkg_node_service_node_servicepb_node_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_node_service_node_servicepb_node_rpc_proto_rawDescData)
	})
	return file_pkg_node_service_node_servicepb_node_rpc_proto_rawDescData
}

var file_pkg_node_service_node_servicepb_node_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_node_service_node_servicepb_node_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_node_service_node_servicepb_node_rpc_proto_goTypes = []interface{}{
	(InitiatorType)(0),       // 0: node_service.InitiatorType
	(*InitiatorRequest)(nil), // 1: node_service.InitiatorRequest
	(*Initiators)(nil),       // 2: node_service.Initiators
	(*UnmappedVolume)(nil),   // 3: node_service.UnmappedVolume
	(*Ack)(nil),              // 4: node_service.Ack
}
var file_pkg_node_service_node_servicepb_node_rpc_proto_depIdxs = []int32{
	0, // 0: node_service.InitiatorRequest.type:type_name -> node_service.InitiatorType
	1, // 1: node_service.NodeService.GetInitiators:input_type -> node_service.InitiatorRequest
	3, // 2: node_service.NodeService.NotifyUnmap:input_type -> node_service.UnmappedVolume
	2, // 3: node_service.NodeService.GetInitiators:output_type -> node_service.Initiators
	4, // 4: node_service.NodeService.NotifyUnmap:output_type -> node_service.Ack
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_node_service_node_servicepb_node_rpc_proto_init() }
func file_pkg_node_service_node_servicepb_node_rpc_proto_init() {
	if File_pkg_node_service_node_servicepb_node_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_node_service_node_servicepb_node_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitiatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_node_service_node_servicepb_node_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Initiators); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_node_service_node_servicepb_node_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnmappedVolume); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_node_service_node_servicepb_node_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_node_service_node_servicepb_node_rpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_node_service_node_servicepb_node_rpc_proto_goTypes,
		DependencyIndexes: file_pkg_node_service_node_servicepb_node_rpc_proto_depIdxs,
		EnumInfos:         file_pkg_node_service_node_servicepb_node_rpc_proto_enumTypes,
		MessageInfos:      file_pkg_node_service_node_servicepb_node_rpc_proto_msgTypes,
	}.Build()
	File_pkg_node_service_node_servicepb_node_rpc_proto = out.File
	file_pkg_node_service_node_servicepb_node_rpc_proto_rawDesc = nil
	file_pkg_node_service_node_servicepb_node_rpc_proto_goTypes = nil
	file_pkg_node_service_node_servicepb_node_rpc_proto_depIdxs = nil
}
